language: go
go: 
  - 1.3.2
  - 1.4.2
  - 1.5.1
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip

before_install:
  - go get -t -v ./...

script:
  - sh test-runner.sh

after_success:
  - bash <(curl -s https://codecov.io/bash)
